const students = [
  {
    id: 1,
    studentId: "DGS2026001",
    name: "Eric Mawule Duadze",
    age: 23,
    gender: "Male",
    email: "eric@example.com",
    phone: "+233 24 123 4567",
    profile: {
      nationality: "Ghanaian",
      city: "Accra",
      address: "East Legon",
    },
    academic: {
      department: "Computer Science",
      course: "Software Engineering",
      level: 300,
      semester: 1,
      gpa: 3.72,
      creditsCompleted: 78,
    },
    courses: [
      {
        id: "CS301",
        name: "Advanced React",
        credit: 3,
        score: 87,
        grade: "A",
      },
      {
        id: "CS302",
        name: "Database Systems",
        credit: 3,
        score: 79,
        grade: "B+",
      },
      {
        id: "CS303",
        name: "Computer Networks",
        credit: 3,
        score: 72,
        grade: "B",
      },
    ],
    attendance: {
      percentage: 94,
      present: 47,
      absent: 3,
      late: 2,
    },
    assignments: [
      {
        id: 101,
        title: "Build a React Dashboard",
        course: "Advanced React",
        dueDate: "2026-08-20",
        completed: true,
        score: 95,
      },
      {
        id: 102,
        title: "Design a PostgreSQL Database",
        course: "Database Systems",
        dueDate: "2026-08-25",
        completed: false,
        score: null,
      },
      {
        id: 103,
        title: "Network Security Research",
        course: "Computer Networks",
        dueDate: "2026-08-30",
        completed: false,
        score: null,
      },
    ],
    fees: {
      total: 6500,
      paid: 4500,
      balance: 2000,
      status: "partial",
    },
    notifications: [
      {
        id: 1,
        title: "Assignment Deadline",
        message: "Database assignment is due soon.",
        read: false,
        date: "2026-08-14",
      },
      {
        id: 2,
        title: "Fee Reminder",
        message: "You have an outstanding balance.",
        read: false,
        date: "2026-08-13",
      },
    ],
    account: {
      role: "student",
      status: "active",
      verified: true,
      lastLogin: "2026-08-14T08:30:00",
    },
  },
  {
    id: 2,
    studentId: "DGS2026002",
    name: "Jessica Kaibobo",
    age: 20,
    gender: "Female",
    email: "jessica@example.com",
    phone: "+233 20 987 6543",
    profile: {
      nationality: "Ghanaian",
      city: "Tema",
      address: "Community 25",
    },
    academic: {
      department: "Information Technology",
      course: "Information Technology",
      level: 200,
      semester: 1,
      gpa: 3.85,
      creditsCompleted: 48,
    },
    courses: [
      {
        id: "IT201",
        name: "Web Development",
        credit: 3,
        score: 91,
        grade: "A",
      },
      {
        id: "IT202",
        name: "Computer Architecture",
        credit: 3,
        score: 84,
        grade: "A-",
      },
      {
        id: "IT203",
        name: "Operating Systems",
        credit: 3,
        score: 76,
        grade: "B+",
      },
    ],
    attendance: {
      percentage: 89,
      present: 42,
      absent: 6,
      late: 4,
    },
    assignments: [
      {
        id: 201,
        title: "Build a Portfolio Website",
        course: "Web Development",
        dueDate: "2026-08-18",
        completed: true,
        score: 92,
      },
      {
        id: 202,
        title: "CPU Architecture Report",
        course: "Computer Architecture",
        dueDate: "2026-08-24",
        completed: false,
        score: null,
      },
    ],
    fees: {
      total: 6000,
      paid: 6000,
      balance: 0,
      status: "paid",
    },
    notifications: [
      {
        id: 3,
        title: "Excellent Attendance",
        message: "Your attendance is currently 89%.",
        read: true,
        date: "2026-08-12",
      },
    ],
    account: {
      role: "student",
      status: "active",
      verified: true,
      lastLogin: "2026-08-13T19:45:00",
    },
  },
  {
    id: 3,
    studentId: "DGS2026003",
    name: "Michael Mensah",
    age: 24,
    gender: "Male",
    email: "michael@example.com",
    phone: "+233 27 456 7890",
    profile: {
      nationality: "Ghanaian",
      city: "Kumasi",
      address: "Ahodwo",
    },
    academic: {
      department: "Computer Science",
      course: "Computer Science",
      level: 400,
      semester: 1,
      gpa: 3.21,
      creditsCompleted: 105,
    },
    courses: [
      {
        id: "CS401",
        name: "Artificial Intelligence",
        credit: 3,
        score: 68,
        grade: "B-",
      },
      {
        id: "CS402",
        name: "Machine Learning",
        credit: 3,
        score: 74,
        grade: "B",
      },
      {
        id: "CS403",
        name: "Software Architecture",
        credit: 3,
        score: 81,
        grade: "A-",
      },
    ],
    attendance: {
      percentage: 76,
      present: 38,
      absent: 12,
      late: 7,
    },
    assignments: [
      {
        id: 301,
        title: "Machine Learning Model",
        course: "Machine Learning",
        dueDate: "2026-08-16",
        completed: false,
        score: null,
      },
      {
        id: 302,
        title: "Software Architecture Diagram",
        course: "Software Architecture",
        dueDate: "2026-08-22",
        completed: true,
        score: 88,
      },
    ],
    fees: {
      total: 7000,
      paid: 3000,
      balance: 4000,
      status: "overdue",
    },
    notifications: [
      {
        id: 4,
        title: "Low Attendance",
        message: "Your attendance has dropped below 80%.",
        read: false,
        date: "2026-08-14",
      },
      {
        id: 5,
        title: "Outstanding Fees",
        message: "Your account has an outstanding balance.",
        read: false,
        date: "2026-08-14",
      },
    ],
    account: {
      role: "student",
      status: "warning",
      verified: true,
      lastLogin: "2026-08-10T14:20:00",
    },
  },
  {
    id: 4,
    studentId: "DGS2026004",
    name: "Ama Serwaa",
    age: 21,
    gender: "Female",
    email: "ama@example.com",
    phone: "+233 55 222 3333",
    profile: {
      nationality: "Ghanaian",
      city: "Cape Coast",
      address: "Abura",
    },
    academic: {
      department: "Data Science",
      course: "Data Science",
      level: 300,
      semester: 1,
      gpa: 3.94,
      creditsCompleted: 75,
    },
    courses: [
      {
        id: "DS301",
        name: "Statistics",
        credit: 3,
        score: 96,
        grade: "A",
      },
      {
        id: "DS302",
        name: "Python for Data Science",
        credit: 3,
        score: 93,
        grade: "A",
      },
      {
        id: "DS303",
        name: "Data Visualization",
        credit: 3,
        score: 89,
        grade: "A-",
      },
    ],
    attendance: {
      percentage: 98,
      present: 49,
      absent: 1,
      late: 0,
    },
    assignments: [
      {
        id: 401,
        title: "Build a Data Visualization",
        course: "Data Visualization",
        dueDate: "2026-08-19",
        completed: true,
        score: 98,
      },
      {
        id: 402,
        title: "Python Data Analysis",
        course: "Python for Data Science",
        dueDate: "2026-08-28",
        completed: false,
        score: null,
      },
    ],
    fees: {
      total: 6500,
      paid: 6500,
      balance: 0,
      status: "paid",
    },
    notifications: [
      {
        id: 6,
        title: "Academic Achievement",
        message: "Your current GPA is 3.94.",
        read: false,
        date: "2026-08-14",
      },
    ],
    account: {
      role: "student",
      status: "active",
      verified: true,
      lastLogin: "2026-08-14T09:15:00",
    },
  },
];
